### ISSUE TITLE
`func-binding` should allow optional param or result

### ISSUE THREAD

**Issue by Hywan** [rustwasm/wasm-webidl-bindings#17]
Since a WebAssembly function can have no parameter or no result, a Web IDL `func-binding` statement should accept that too.

I don't know whether Web IDL supports that already, but the `grammar.lalrpop` require a `(param …)` and a `(result …)` declarations.

We can expect the following statement to be valid:

```
func-binding $encodeIntoBinding import $log_message_wasm_type $log_message_webidl_type
    (param
        (utf8-cstr ByteString 0))
```

**Comment by fitzgen** [comment]
Yep, PRs welcome!

**Comment by Hywan** [comment]
I'll probably open a PR for that, just wanted to open the issue so that I don't forget about it :-).
