### ISSUE TITLE
Decode binary form

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-webidl-bindings#5]
We can parse the straw proposal text form, next up is doing the same for a straw proposal binary encoding.

**Comment by Hywan** [comment]
Ideally, we should use LALRPOP, or you prefer to use another tool?

**Comment by fitzgen** [comment]
I'm working on a PR now; not using any parser framework for the binary decoding.

**Comment by Hywan** [comment]
Ah. I also have a PR almost ready. I give you the priority then.

**Comment by Hywan** [comment]
Can be closed, #20 has been merged.
