### ISSUE TITLE
Split the text format parser into its own crate

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-webidl-bindings#9]
`lalrpop` and its generated code can take a while to compile, and I'd like to add a moat between it and the rest of the project.

We should move `src/text/{grammar.lalrpop, parser.rs, actions.rs}` to a new crate: `crates/text-parser`. The crate name should be `wasm-webidl-bindings-text-parser`. Otherwise it should basically remain the same. We can re-export its functionality in `src/text/mod.rs`.

**Comment by ghost** [comment]
I would like to try this one.
